### ISSUE TITLE
https://demo.bitcaster.io/os4d/me/events/

### ISSUE THREAD

**Issue by hemantsapkal** [bitcaster-io/bitcaster#33]
**Describe the bug**

**To Reproduce**
1. Go to 'Task Bar and '
2. Click on 'Notification log...'
 client authentication '403 error comes' need to be corrected as the feedback button is disable on the error screen.
  

<!DOCTYPE html>
--
  | <html lang="en">
  | <head>
  | <meta charset="UTF-8">
  | <title>FORBIDDEN</title>
  | <link rel="shortcut icon" type="image/png" href="/images/favicon.ico"/>
  | <link rel="stylesheet" href="/static/bitcaster/bitcaster.css?0.63.0a  ">
  | <script src="https://code.jquery.com/jquery-1.12.4.min.js"
  | integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
  |  
  | </head>
  | <body class="">
  | <h1 class="p-5">bitcaster</h1>
  | <div class="row pl-5 ">
  | <div class="col-7">
  | <h3><b>403. </b>Forbidden</h3>
  | <h4>The client has insufficient authentication credentials for the server to process this request.</h4>
  |  
  | <div style="padding: 5px;display: block">&#39;manage_organization&#39;</div>
  |  
  | <div style="margin-top: 50px;margin-bottom:50px;display: block">
  |  
  | <h4>If you need assistance, you may reference this error as
  | <strong>3601559a0db44bd3b20c22b2de71c56b</strong>.</h4>
  | <button style="padding: 10px" class="error_feedback">Add Feedback</button>
  |  
  | </div>
  |  
  |  
  | <h4 class="pt-5"><a href="https://demo.bitcaster.io/os4d/me/events/">Back</a></h4>
  |  
  | </div>
  | <div class="col-4">
  | <img src="/static/bitcaster/images/bitcaster100.png?0.63.0a  ">
  | </div>
  | </div>
  |  
  |  
  | <script src="https://browser.sentry-cdn.com/4.6.4/bundle.min.js" crossorigin="anonymous"></script>
  | <script>
  | (function ($) {
  | $('.error_feedback').click(function () {
  | Sentry.init({dsn: 'http://80350690f3914f4f8778cee3ce8663c0@sentry:9000/2'});
  | Sentry.showReportDialog({
  | eventId: '3601559a0db44bd3b20c22b2de71c56b',
  | user: {
  | email: "bitcastertest@gmail.com",
  | name: "Heman"
  | },
  | subtitle: "",
  |  
  | });
  | });
  | })(jQuery);
  | </script>
  |  
  |  
  |  
  |  
  | </body>
  | </html>

**Expected behavior**
User should get messages to ask for admin for access to see notification logs. and in this case application owner user role should have this access.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by saxix** [comment]
fixed in 0.64.0a
