### ISSUE TITLE
Skype Send Code error 

### ISSUE THREAD

**Issue by hemantsapkal** [bitcaster-io/bitcaster#35]
**Describe the bug**

**To Reproduce**
1. Go to 'Addresses'
2. Click on 'verify'
3. Scroll down to click on send code
4. See error, please
![Skype_Send_code_error](https://user-images.githubusercontent.com/24444467/59160148-c7b3ff80-8aca-11e9-8762-193d0324be92.JPG)
 find an attached error.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by saxix** [comment]
is the email address a valid Skype account ?

**Comment by hemantsapkal** [comment]
Yes email address is valid for Skype. I have created new one and loged in to test 

Sent from Yahoo Mail on Android 
 
  On Sun, 9 Jun 2019 at 9:09 pm, Stefano Apostolico<notifications@github.com> wrote:   
is the email address a valid Skype account ?
