### ISSUE TITLE
'Delete' bug in address/assignments

### ISSUE THREAD

**Issue by jspandolfo** [bitcaster-io/bitcaster#38]
**Describe the bug**
In 'addresses', while inserting a new assignment and, by mistake, inserting an already existing channel, the 'delete' function does not work properly

**To Reproduce**
1. Go to 'addresses'=> 'assignments'
2. Click on 'Add assignment' and insert an already existing channel and address
3. click on 'save', the error message appears
4. Delete the preexisting channel and click 'save'
5. The same error message appears, and the deleted channel returns to the list
6. Delete the newly added channel, click 'save', and both channels disappear from the list

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by saxix** [comment]
invalid in current version
