### ISSUE TITLE
Bug: Notification is received by the user even if Assignment is not validated

### ISSUE THREAD

**Issue by SimoMart88** [bitcaster-io/bitcaster#4]
Possible bug, investigation required.

**How to replicate:**
- Follow instructions in CONTRIB documentation
- Follow instructions in Quickstart documentation
- Trigger an Event

**Unexpected behavior:**
- Notification is received by the user even if the Assignment has not been validated

**Expected behavior:**
- User doesn't receive any notification until the Assignment has been properly validated

**Hints:**
- AddressManager.valid() method seams defined but never used

**Comment by hanarero** [comment]
This is currently an expected behaviour
