### ISSUE TITLE
Enhancement proposal - explain the line "F" at the bottom of profile section

### ISSUE THREAD

**Issue by jspandolfo** [bitcaster-io/bitcaster#41]
Under 'profile', at the bottom there is a line named 'F' with a sort of key as content. It is not clear what it stands for.

**Comment by saxix** [comment]
is still valid in version 0.79.0a ?

**Comment by jspandolfo** [comment]
Still valid at the moment.

**Comment by saxix** [comment]
fixed in 0.89
