### ISSUE TITLE
Bug in creating new event

### ISSUE THREAD

**Issue by jspandolfo** [bitcaster-io/bitcaster#43]
**Describe the bug**
Not able to create a new event - text cannot be saved, buttons in the upper right menu bar cannot be activated, instead they delete all the unsaved changes and bring to an empty 'create event' page

**To Reproduce**
1. Go to 'Admin OS4D'-> 'Applications'->'Josi test'->Events
2. Click on 'Add event'. Screenshot shows the appearance of the menu bar:

![Screenshot](https://user-images.githubusercontent.com/51872146/59689034-2a01b400-91df-11e9-81bf-edce51314c9d.png)

3. Fill in the obligatory fields, click 'save' or 'save and edit' - > no notification shows that the changes have been saved

4. Try to turn on 'enable', 'debug mode' or any other button in the menu -  all the text of the event is deleted

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by saxix** [comment]
fixed in 0.78
