### ISSUE TITLE
Bug with deleting a new address

### ISSUE THREAD

**Issue by jspandolfo** [bitcaster-io/bitcaster#47]
**Describe the bug**
Not able to delete a newly added address ,

**To Reproduce**
1. Go to user 'addresses'
2. Create a new address (without validating it)
3. Click on the icon to delete it
4. The following appears:
![Screenshot from 2019-06-19 20-54-07](https://user-images.githubusercontent.com/51872146/59793202-3fa5d500-92d6-11e9-85ec-cb4818a0162c.png)
 
After changing the page and going back to it, I found that the address was deleted, it was no longer on the list of addresses.

Trying to repeat the action, to confirm the bug, I clicked on the delete button for another (unvalidated) address. This time there was no 404, the system went on as normally saying 'the action is not reversable', returned to the list of addresses; the 'deleted' notification in the upper right corner was "loading" very slowly (the grey line under the letters), and once finished, the address was not deleted, it stayed on the list.

Then I went to 'verify addresses', it tells me all are verified.
I go back to 'addresses', the one I tried to delete is now deleted.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by saxix** [comment]
fixed in 0.89
