### ISSUE TITLE
Address lost the pairing with its channel

### ISSUE THREAD

**Issue by jspandolfo** [bitcaster-io/bitcaster#48]
**Describe the bug**
Tried to subscribe to an event (as admin), the system tells me I don't have an address assigned to the channel that the event uses, or it is not validated, which was not true - The event used gmail, I had it among my addresses, verified. 

However, on my list of addresses,  my gmail address was not connected to any channel, and it was not on my list for "addresses verification" as invalid.

The pairing disappeared..? 

Once I entered 'edit address', it showed me the following:

![Screenshot from 2019-06-19 21-45-52](https://user-images.githubusercontent.com/51872146/59796788-88618c00-92de-11e9-8c89-4df16223f7fd.png)

..I paired it with gmail and successfully subscribed to the event.

For all of my previous subscriptions I had to do the same thing, to pair the addresses with channels, otherwise under 'deliver to' it stated 'invalid subscription'.

![Screenshot from 2019-06-19 22-14-01](https://user-images.githubusercontent.com/51872146/59797469-096d5300-92e0-11e9-8c32-25e9bf59f1a4.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by saxix** [comment]
fixed in 0.89

**Comment by jspandolfo** [comment]
Again, the channel loses its address: 
![Screenshot from 2019-06-20 22-41-15](https://user-images.githubusercontent.com/51872146/59880599-b19d1d80-93ad-11e9-943f-8be6846f4ced.png)

here, with status 10:
![Screenshot from 2019-06-20 22-10-41](https://user-images.githubusercontent.com/51872146/59880721-0a6cb600-93ae-11e9-8139-a7f0d19f9b4c.png)

I go to 'edit subscription' and insert the missing link channel/address, and it is all ok again.
