### ISSUE TITLE
Organization image fails to load

### ISSUE THREAD

**Issue by GigiusB** [bitcaster-io/bitcaster#5]
**Describe the bug**
Tried unsuccessfully to load orgnaization logo

**To Reproduce**
1. Go to organisation/configuration
2. Click on 'chose file' to select an image
3. Click save

**Expected behavior**
The appropriate image is loaded and displayed

**Screenshots**
![selection_006](https://user-images.githubusercontent.com/863738/52591527-12cf4600-2e3c-11e9-9937-7eba74ec065e.png)

**Comment by saxix** [comment]
fixed in 41fcdfd
