### ISSUE TITLE
When trying github authetication it redirects to localhost.

### ISSUE THREAD

**Issue by ElisaBro** [bitcaster-io/bitcaster#9]
**Describe the bug**
As per subject.

**Expected behavior**
It should allow authentication with github.

**Screenshots**
<img width="796" alt="Capture" src="https://user-images.githubusercontent.com/49231706/55508320-909c1a80-5651-11e9-912a-964a6822409e.PNG">

**Comment by GigiusB** [comment]
It was an error in the setup configuration
